# Numpy

### Numpy vs List

In [1]:
list1 = [12,23,34,45,56,67,89]

In [1]:
import numpy as np

In [3]:
arr1 = np.array(list1)

In [4]:
type(list1)

list

In [5]:
type(arr1)

numpy.ndarray

In [6]:
print(list1)

[12, 23, 34, 45, 56, 67, 89]


In [7]:
print(arr1)

[12 23 34 45 56 67 89]


In [8]:
list2 = [12, 23, 34, 45, 56, 67, 89, "Hello", "Bye"]

In [9]:
arr2 = np.array(list2)

In [10]:
print(list2)

[12, 23, 34, 45, 56, 67, 89, 'Hello', 'Bye']


In [11]:
print(arr2)

['12' '23' '34' '45' '56' '67' '89' 'Hello' 'Bye']


In [12]:
list3 = [12, 23, 34, 45, 56, 67, 89, "Hello", "Bye", True, False]

In [13]:
arr3 = np.array(list3)

In [14]:
print(arr3)

['12' '23' '34' '45' '56' '67' '89' 'Hello' 'Bye' 'True' 'False']


In [15]:
list4 = [12, 23, 34, 45, 56, 67, 89, True, False]

In [16]:
arr4 = np.array(list4)

In [17]:
print(arr4)

[12 23 34 45 56 67 89  1  0]


In [19]:
list5 = [12, 23, 34, 45, 56, 67, 89.9, True, False]

In [20]:
arr5 = np.array(list5)

In [21]:
print(arr5)

[12.  23.  34.  45.  56.  67.  89.9  1.   0. ]


String > Float > Integer > Boolean

In [22]:
list6 = [True, False]

In [23]:
arr6 = np.array(list6)

In [24]:
print(arr6)

[ True False]


In [25]:
import sys

In [26]:
sys.getsizeof([])

64

In [27]:
sys.getsizeof(np.array([]))

96

In [28]:
new_list = list(range(100))

In [29]:
print(new_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [30]:
sys.getsizeof(new_list)

1008

In [31]:
new_arr = np.array(new_list)

In [32]:
sys.getsizeof(new_arr)

896

In [33]:
new_list = list(range(100000))

In [34]:
sys.getsizeof(new_list)

900112

In [35]:
new_arr = np.array(new_list)

In [36]:
sys.getsizeof(new_arr)

800096

### Ways to create Numpy array

In [3]:
#1. Using np.array()
list1 = [1,2,3,4,5]
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.array([i for i in range(1,101) if i % 2 == 0])
arr2

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [5]:
#2. Using np.arange()
arr3 = np.arange(1,101)
arr3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [22]:
#3. Using linear-space
np.linspace(1,100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [23]:
np.linspace(1,100,retstep=True,num=25,endpoint=False)

(array([ 1.  ,  4.96,  8.92, 12.88, 16.84, 20.8 , 24.76, 28.72, 32.68,
        36.64, 40.6 , 44.56, 48.52, 52.48, 56.44, 60.4 , 64.36, 68.32,
        72.28, 76.24, 80.2 , 84.16, 88.12, 92.08, 96.04]), 3.96)

In [25]:
#4. Using random values (floating values)
np.random.random()

0.804517323807435

In [26]:
np.random.random(5)

array([0.94906688, 0.44272291, 0.83163487, 0.09410814, 0.94072588])

In [27]:
np.random.random((4,5))

array([[0.41664202, 0.44948928, 0.31299785, 0.75541116, 0.17039183],
       [0.36460887, 0.53163106, 0.96315302, 0.47464651, 0.07876503],
       [0.8977536 , 0.13876116, 0.65934608, 0.68473497, 0.48549275],
       [0.91528316, 0.75253616, 0.29080909, 0.8057924 , 0.56503891]])

In [28]:
np.random.random((3,4,5))

array([[[0.47840068, 0.40323999, 0.56053694, 0.50939841, 0.40323715],
        [0.31590502, 0.74601916, 0.21624136, 0.46235789, 0.19464613],
        [0.59328281, 0.69520112, 0.30297704, 0.63734283, 0.70504603],
        [0.85459604, 0.04989688, 0.96889251, 0.56147463, 0.45874162]],

       [[0.52439677, 0.30136199, 0.9296788 , 0.26849275, 0.40749121],
        [0.50474749, 0.07400942, 0.9014765 , 0.19780418, 0.92193943],
        [0.52054783, 0.06128592, 0.28182119, 0.69884786, 0.69202707],
        [0.13299058, 0.4510185 , 0.21731804, 0.500313  , 0.08588395]],

       [[0.75683724, 0.71744689, 0.68832404, 0.1498433 , 0.34125445],
        [0.81212639, 0.40014538, 0.1478284 , 0.26578703, 0.08558618],
        [0.35971508, 0.7716116 , 0.1641019 , 0.73602234, 0.5286221 ],
        [0.39865441, 0.05409146, 0.89931484, 0.8006578 , 0.77311057]]])

In [30]:
np.random.random((2,3,4,5))

array([[[[0.02479164, 0.55453886, 0.67431166, 0.56904956, 0.43482284],
         [0.89120151, 0.79764771, 0.55708931, 0.86215947, 0.36823923],
         [0.58629041, 0.24748894, 0.13388461, 0.14880368, 0.49506852],
         [0.47194915, 0.16439132, 0.00238861, 0.58115877, 0.42864952]],

        [[0.6356118 , 0.56851166, 0.19180007, 0.10371946, 0.534553  ],
         [0.833712  , 0.37178617, 0.0024297 , 0.70386768, 0.97937415],
         [0.90402703, 0.72876224, 0.93214712, 0.69153283, 0.72090895],
         [0.9028595 , 0.59536686, 0.42666332, 0.04763033, 0.44379452]],

        [[0.89207334, 0.29118826, 0.44686465, 0.03863581, 0.15684859],
         [0.19766827, 0.1715397 , 0.75974926, 0.03248255, 0.38817532],
         [0.7969742 , 0.90855546, 0.01417756, 0.64698406, 0.17189359],
         [0.27987638, 0.06877288, 0.91205069, 0.1322504 , 0.93754618]]],


       [[[0.06608823, 0.12780961, 0.7370646 , 0.47344059, 0.31606049],
         [0.05833687, 0.13694016, 0.27340494, 0.74478855, 0.95698732]

In [37]:
#5. Generating same random numbers everywhere
np.random.seed(5)

In [38]:
np.random.random()

0.22199317108973948

In [39]:
np.random.random(5)

array([0.87073231, 0.20671916, 0.91861091, 0.48841119, 0.61174386])

In [45]:
#6. Generating random integers
np.random.randint(100)

80

In [48]:
np.random.randint(100,1000)

213

In [49]:
np.random.randint(100,1000, (5))

array([537, 180, 127, 144, 305])

In [50]:
np.random.randint(100,1000, (4,5))

array([[815, 165, 531, 642, 186],
       [737, 246, 354, 477, 749],
       [462, 141, 546, 997, 310],
       [203, 244, 105, 926, 868]])

In [51]:
np.random.randint(100,1000, (3,4,5))

array([[[210, 776, 973, 791, 639],
        [899, 870, 424, 394, 205],
        [247, 374, 981, 345, 235],
        [968, 464, 721, 770, 290]],

       [[879, 591, 935, 480, 549],
        [283, 487, 703, 178, 901],
        [829, 953, 491, 628, 194],
        [114, 899, 365, 650, 915]],

       [[244, 489, 518, 785, 799],
        [508, 497, 474, 335, 844],
        [131, 132, 432, 272, 498],
        [275, 194, 950, 996, 235]]])

### Numpy Methods

In [57]:
new_arr = np.random.randint(10,1000,100)

In [58]:
new_arr

array([700, 608, 541, 576, 930, 714,  87, 595, 907, 275, 330, 626, 417,
       177, 899, 718, 761, 475, 101, 558, 124, 875,  97,  79, 262, 942,
       924, 300,  40, 599, 619, 892, 813,  39, 779,  92,  30, 243, 650,
       635, 940, 216, 445, 424, 818,  84, 463, 345, 191, 894, 413, 440,
       164, 771, 607, 227, 768, 579, 239, 411, 872, 123, 202, 422, 914,
       903, 152, 202, 297, 183, 655, 420, 947, 221, 294, 469, 557, 506,
       989, 961, 781, 545, 909, 105,  12, 576, 999, 688, 412, 377, 977,
       202, 941, 390, 385, 559,  11, 424, 101, 681])

In [56]:
new_arr.sort()

In [55]:
new_arr

array([ 23,  32,  39,  46,  54,  73,  74,  80,  92, 104, 110, 120, 140,
       146, 156, 170, 179, 181, 187, 190, 210, 212, 220, 224, 226, 230,
       235, 253, 265, 267, 270, 274, 280, 281, 286, 286, 318, 347, 382,
       388, 403, 463, 465, 469, 484, 486, 501, 507, 517, 521, 530, 538,
       544, 553, 557, 557, 579, 594, 616, 642, 643, 648, 665, 669, 670,
       682, 682, 687, 695, 710, 712, 715, 716, 722, 729, 732, 737, 755,
       761, 778, 788, 790, 836, 837, 847, 848, 869, 870, 889, 902, 908,
       911, 928, 929, 955, 970, 989, 989, 992, 997])

In [65]:
new_arr = np.random.randint(10,1000,(3,4,5))

In [66]:
new_arr.size

60

In [67]:
new_arr

array([[[399, 854, 771, 251, 439],
        [ 89, 162,  48, 278, 907],
        [ 15, 539, 533,  98, 386],
        [247, 706, 221, 548, 381]],

       [[308, 835, 225, 314, 501],
        [274, 532,  49, 781, 950],
        [846, 360,  65, 937, 676],
        [106, 791, 214, 503, 192]],

       [[349, 916, 171, 751, 619],
        [714, 765, 886, 942, 582],
        [ 10, 338, 509, 290, 164],
        [ 15, 423, 201,  28, 321]]])

In [68]:
new_arr.shape

(3, 4, 5)

In [69]:
new_arr.resize(6,10) #reshapes the original array

In [70]:
new_arr

array([[399, 854, 771, 251, 439,  89, 162,  48, 278, 907],
       [ 15, 539, 533,  98, 386, 247, 706, 221, 548, 381],
       [308, 835, 225, 314, 501, 274, 532,  49, 781, 950],
       [846, 360,  65, 937, 676, 106, 791, 214, 503, 192],
       [349, 916, 171, 751, 619, 714, 765, 886, 942, 582],
       [ 10, 338, 509, 290, 164,  15, 423, 201,  28, 321]])

In [72]:
new_arr.shape

(6, 10)

In [71]:
new_arr.reshape(10,6)  #reshape the copy of array

array([[399, 854, 771, 251, 439,  89],
       [162,  48, 278, 907,  15, 539],
       [533,  98, 386, 247, 706, 221],
       [548, 381, 308, 835, 225, 314],
       [501, 274, 532,  49, 781, 950],
       [846, 360,  65, 937, 676, 106],
       [791, 214, 503, 192, 349, 916],
       [171, 751, 619, 714, 765, 886],
       [942, 582,  10, 338, 509, 290],
       [164,  15, 423, 201,  28, 321]])

In [73]:
new_arr.shape

(6, 10)

In [74]:
new_arr.ravel() #converts 2-d or 3-d array into 1-d

array([399, 854, 771, 251, 439,  89, 162,  48, 278, 907,  15, 539, 533,
        98, 386, 247, 706, 221, 548, 381, 308, 835, 225, 314, 501, 274,
       532,  49, 781, 950, 846, 360,  65, 937, 676, 106, 791, 214, 503,
       192, 349, 916, 171, 751, 619, 714, 765, 886, 942, 582,  10, 338,
       509, 290, 164,  15, 423, 201,  28, 321])

In [75]:
new_arr.ndim

2

In [76]:
new_arr.resize(3,2,10)

In [77]:
new_arr

array([[[399, 854, 771, 251, 439,  89, 162,  48, 278, 907],
        [ 15, 539, 533,  98, 386, 247, 706, 221, 548, 381]],

       [[308, 835, 225, 314, 501, 274, 532,  49, 781, 950],
        [846, 360,  65, 937, 676, 106, 791, 214, 503, 192]],

       [[349, 916, 171, 751, 619, 714, 765, 886, 942, 582],
        [ 10, 338, 509, 290, 164,  15, 423, 201,  28, 321]]])

In [78]:
new_arr.ndim

3

In [79]:
new_arr.min()

10

In [80]:
new_arr.max()

950

In [81]:
new_arr.mean()

438.75

In [82]:
new_arr.flatten()

array([399, 854, 771, 251, 439,  89, 162,  48, 278, 907,  15, 539, 533,
        98, 386, 247, 706, 221, 548, 381, 308, 835, 225, 314, 501, 274,
       532,  49, 781, 950, 846, 360,  65, 937, 676, 106, 791, 214, 503,
       192, 349, 916, 171, 751, 619, 714, 765, 886, 942, 582,  10, 338,
       509, 290, 164,  15, 423, 201,  28, 321])

In [84]:
new_arr.resize(60)

In [85]:
new_arr

array([399, 854, 771, 251, 439,  89, 162,  48, 278, 907,  15, 539, 533,
        98, 386, 247, 706, 221, 548, 381, 308, 835, 225, 314, 501, 274,
       532,  49, 781, 950, 846, 360,  65, 937, 676, 106, 791, 214, 503,
       192, 349, 916, 171, 751, 619, 714, 765, 886, 942, 582,  10, 338,
       509, 290, 164,  15, 423, 201,  28, 321])

In [86]:
new_arr.argsort()

array([50, 55, 10, 58,  7, 27, 32,  5, 13, 35,  6, 54, 42, 39, 57, 37, 17,
       22, 15,  3, 25,  8, 53, 20, 23, 59, 51, 40, 31, 19, 14,  0, 56,  4,
       24, 38, 52, 26, 12, 11, 18, 49, 44, 34, 16, 45, 43, 46,  2, 28, 36,
       21, 30,  1, 47,  9, 41, 33, 48, 29])

In [87]:
new_arr[50]

10

In [88]:
new_arr[29]

950

In [89]:
new_arr.argmin()

50

In [90]:
new_arr.argmax()

29