In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
#sklearn - scikit learn

In [2]:
dataset = pd.read_csv('SaratogaHouses.csv')

In [3]:
x = dataset["livingArea"].values
y = dataset["price"].values

In [4]:
x.ndim, y.ndim

(1, 1)

In [5]:
x[:10]

array([ 906, 1953, 1944, 1944,  840, 1152, 2752, 1662, 1632, 1416])

In [6]:
# x.resize(len(x),1)
x = x.reshape([-1,1])

In [7]:
x[:10]

array([[ 906],
       [1953],
       [1944],
       [1944],
       [ 840],
       [1152],
       [2752],
       [1662],
       [1632],
       [1416]])

In [8]:
x.ndim

2

In [9]:
linear_regression = LinearRegression()
linear_regression.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
linear_regression.coef_

array([113.12254185])

In [11]:
linear_regression.intercept_

13439.394004889502

In [12]:
y_predictions = linear_regression.predict(x)

In [13]:
y_predictions[:10]

array([115928.4169181 , 234367.71823171, 233349.61535509, 233349.61535509,
       108462.32915621, 143756.56221241, 324752.62916731, 201449.05855429,
       198055.38229888, 173620.91325997])

In [14]:
y[:10]

array([132500, 181115, 109000, 155000,  86060, 120000, 153000, 170000,
        90000, 122900])

In [15]:
from sklearn.metrics import mean_squared_error

In [16]:
mse = mean_squared_error(y,y_predictions)
print(mse)

4769912967.014986


In [17]:
np.sqrt(mse)

69064.55651790567

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [20]:
print(len(x_train))
print(len(x_test))
print(len(y_train))
print(len(y_test))

1382
346
1382
346


In [21]:
linear_regression2 = LinearRegression()
linear_regression2.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
linear_regression2.coef_

array([112.09660381])

In [23]:
linear_regression2.intercept_

15766.577439429762

In [24]:
y_predictions_test_data = linear_regression2.predict(x_test)

In [25]:
mse = mean_squared_error(y_test, y_predictions_test_data)
print(mse)

4756792641.088484


In [26]:
np.sqrt(mse)

68969.5051532812

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
std = StandardScaler()

In [29]:
x.shape

(1728, 1)

In [30]:
x[:10]

array([[ 906],
       [1953],
       [1944],
       [1944],
       [ 840],
       [1152],
       [2752],
       [1662],
       [1632],
       [1416]])

In [31]:
x = std.fit_transform(x)

In [32]:
x[:10]

array([[-1.36985441],
       [ 0.31951971],
       [ 0.30499787],
       [ 0.30499787],
       [-1.47634791],
       [-0.9729241 ],
       [ 1.60873645],
       [-0.1500198 ],
       [-0.19842594],
       [-0.54695011]])

In [33]:
x.min(), x.max()

(-1.837780390181007, 5.603856161728951)

In [40]:
y = y.reshape([-1,1])
y = std.fit_transform(y)

In [41]:
y[:10]

array([[-0.80748259],
       [-0.31349249],
       [-1.04627242],
       [-0.57885403],
       [-1.27937193],
       [-0.93449845],
       [-0.59917657],
       [-0.42643499],
       [-1.23933653],
       [-0.90503077]])

In [42]:
y.min(), y.max()

(-2.103044415654399, 5.721132891573342)

In [45]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)
linear_regression3 = LinearRegression()
linear_regression3.fit(x_train, y_train)
y_predictions_test_data = linear_regression3.predict(x_test)
mse = mean_squared_error(y_test, y_predictions_test_data)
print(mse)

0.7014258245421203


In [46]:
np.sqrt(mse)

0.8375116862122703